
[tox]
envlist = py{38,39,310,311}-django{22,32,40,41,42}, py39-flake8, py39-coverage

[gh-actions]
python =
    3.8: py38
    3.9: py39
    3.10: py310
    3.11: py311

[testenv:py39-flake8]
deps =
    flake8
    flake8-print
commands = flake8

[testenv:py39-django32-coverage]
allowlist_externals = echo
commands =
    # https://github.com/nedbat/coveragepy/issues/1272
    pip install coverage<6
    coverage erase
    coverage run ./manage.py test
    coverage report --include='admin_sort*' --omit='*/tests/*'
    coverage html --include='admin_sort*' --omit='*/tests/*'
    echo "opener htmlcov/index.html"

[testenv]
commands = python manage.py test
setenv =
    DJANGO_SETTINGS_MODULE=admin_sort.tests.settings
    PYTHONPATH={toxinidir}
deps =
    django22: Django>=2.2,<2.3
    django32: Django>=3.2,<4
    django40: Django>=4,<4.1
    django41: Django>=4.1,<4.2
    django42: Django>=4.2,<5
    django-appconf
    selenium<4.0.0
# https://stackoverflow.com/questions/70821737/webdriverexception-message-service-geckodriver-unexpectedly-exited-status-cod

[testenv:py37-django40]
allowlist_externals = echo
deps =
commands= echo "no django 4.0 on python 3.7!"
